# Generated by Django 4.0.3 on 2022-03-29 18:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Reference',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_available', models.BooleanField(default=True)),
                ('name', models.CharField(max_length=256)),
                ('section', models.CharField(max_length=64)),
                ('type', models.CharField(choices=[('RF', 'Funcional'), ('RNF', 'Não-funcional')], default='RF', max_length=4)),
            ],
        ),
        migrations.CreateModel(
            name='Requirement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('author', models.CharField(max_length=64)),
                ('type', models.CharField(blank=True, choices=[('RF', 'Funcional'), ('RNF', 'Não-funcional')], default='RF', max_length=4, null=True)),
                ('section', models.CharField(blank=True, max_length=64, null=True)),
                ('name', models.CharField(max_length=256)),
                ('category', models.CharField(max_length=64)),
                ('date', models.DateField(auto_now_add=True)),
                ('version', models.IntegerField(default=1)),
                ('priority', models.CharField(default='Essencial', max_length=64)),
                ('description', models.TextField(max_length=16384)),
                ('reference', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='requirement', to='base.reference')),
            ],
        ),
    ]
