# Generated by Django 4.0.3 on 2022-03-29 17:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0002_alter_available_name_alter_requirement_category_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Reference',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_available', models.BooleanField(default=True)),
                ('name', models.CharField(max_length=256)),
                ('section', models.CharField(max_length=64)),
                ('type', models.CharField(choices=[('RF', 'Funcional'), ('RNF', 'Não-funcional')], default='RF', max_length=4)),
            ],
        ),
        migrations.AddField(
            model_name='requirement',
            name='section',
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
        migrations.AlterField(
            model_name='requirement',
            name='reference',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='requirement', to='base.reference'),
        ),
        migrations.DeleteModel(
            name='Available',
        ),
    ]
