# Generated by Django 4.0.4 on 2022-06-04 00:44

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0003_passwordresetrequest'),
    ]

    operations = [
        migrations.CreateModel(
            name='WasteCollectionRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('address', models.CharField(max_length=2048)),
                ('kilogram_amount', models.DecimalField(decimal_places=2, max_digits=5)),
                ('desired_collection_date', models.DateField()),
                ('waste_type', models.CharField(choices=[('ABS', 'ABS Plastic (acrylonitrile butadiene styrene)'), ('Al', 'Aluminum'), ('PET', 'PET Plastic (polyethylene terephthalate)')], default='Al', max_length=3)),
                ('status', models.CharField(choices=[('A', 'Request accepted.'), ('P', 'Request pending.'), ('R', 'Request rejected.')], default='P', max_length=1)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='collection_requests', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
