# Generated by Django 4.2.4 on 2023-08-20 03:07

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("base", "0004_wastecollectionrequest"),
    ]

    operations = [
        migrations.AlterField(
            model_name="wastecollectionrequest",
            name="waste_type",
            field=models.CharField(
                choices=[
                    ("ABS", "ABS Plastic (acrylonitrile butadiene styrene)"),
                    ("ALU", "Aluminum"),
                    ("PET", "PET Plastic (polyethylene terephthalate)"),
                ],
                default="ALU",
                max_length=3,
            ),
        ),
    ]
